### ISSUE TITLE
Fix the jumpiness between sites with/without scrollbars

### ISSUE THREAD

**Issue by href** [seantis/lektor-seantis-website#8]
Use the fix we have in place for OneGov Cloud sites:

``` scss
/*
    get rid of the jump that is introduced when switching from a site with
    scrollbar to a site without (or vice versa)

    (100vw includes the scrollbar, 100% does not)
*/
html {
    @media not print {
        margin-left: calc(100vw - 100%);
    }
}
```
